language: node_js

sudo: false

node_js:
  - "stable"

install:
  - "npm install yarn -g"
  - "yarn install"
  - "yarn global add codeclimate-test-reporter"

before_script:
  - "export TZ=Europe/Warsaw"

after_success:
  - "npm run coverage"
  - "codeclimate-test-reporter < coverage/lcov.info"
